# Random Variables

Frequently, when an experiment is performed, we are interested mainly in some function of the outcome as opposed to the actual outcome itself.

For instance,<br>
1) In recent flipping a coin experiment, we may be interested in the total number of heads that occur and not care at all about the actual **Head(H)â€“Tail(T)** sequence that results. <br>

2) In throwing dice, we are often interested in the sum of the two dice and are not really concerned about the separate values of each die. That is, we may be interested in knowingthat the sum is 7 and may not be concerned over whether the actual outcome was: (1, 6), (2, 5), (3, 4), (4, 3), (5, 2), or (6, 1). <br>

Also, These quantities of interest, or, more formally, these real-valued functions defined on the sample space, are known as '**Random Variables**'.

## Lets do an experiment with Python to demostrate 
> ### *Why we need Random Variables?*

## & show its importance

In [19]:
import numpy as np
import pandas as pd
from itertools import product
# from IPython.core.display import HTML
# css = open('media/style-table.css').read() + open('media/style-notebook.css').read()
# HTML('<style>{}</style>'.format(css))

In [20]:
one_toss = np.array(['H', 'T'])

In [21]:
two_tosses = list(product(one_toss, repeat=2))
two_tosses

[('H', 'H'), ('H', 'T'), ('T', 'H'), ('T', 'T')]

In [22]:
# For three tosses, just change the number of repetitions:
three_tosses = list(product(one_toss, repeat=3))
three_tosses

[('H', 'H', 'H'),
 ('H', 'H', 'T'),
 ('H', 'T', 'H'),
 ('H', 'T', 'T'),
 ('T', 'H', 'H'),
 ('T', 'H', 'T'),
 ('T', 'T', 'H'),
 ('T', 'T', 'T')]

As shown earlier in slide,<br>
A *probability space* $(\Omega, P)$ is an outcome space accompanied by the probabilities of all the outcomes.
<br>If you assume all eight outcomes of three tosses are equally likely, the probabilities are all 1/8:

In [23]:
three_toss_probs = (1/8)*np.ones(8)

In [24]:
three_toss_space = pd.DataFrame({
    'Omega':three_tosses,
    'P(omega)':three_toss_probs
})
three_toss_space

       Omega  P(omega)
0  (H, H, H)     0.125
1  (H, H, T)     0.125
2  (H, T, H)     0.125
3  (H, T, T)     0.125
4  (T, H, H)     0.125
5  (T, H, T)     0.125
6  (T, T, H)     0.125
7  (T, T, T)     0.125

As you can see above, Product spaces(Probability spaces) get large very quickly. 
If we are tossing 10 times, the outcome space would consist of the $2^{10}$  sequences of 10 elements where each element is H or T. <br>
The outcomes are a pain to list by hand, but computers are good at saving us that kind of pain.

Lets take example of rolling die,<br>
If we roll a die 5 times, there are almost 8,000 possible outcomes:

In [52]:
die = np.arange(1, 7, 1)
five_rolls = list(product(die, repeat=5))
# five_rolls = [list(i) for i in product(die, repeat=5)]
five_roll_probs = (1/6**5)**np.ones(6**5)
five_roll_space = pd.DataFrame({
   'Omega':five_rolls,
    'P(omega)':five_roll_probs
})
five_roll_space

                Omega  P(omega)
0     (1, 1, 1, 1, 1)  0.000129
1     (1, 1, 1, 1, 2)  0.000129
2     (1, 1, 1, 1, 3)  0.000129
3     (1, 1, 1, 1, 4)  0.000129
4     (1, 1, 1, 1, 5)  0.000129
5     (1, 1, 1, 1, 6)  0.000129
6     (1, 1, 1, 2, 1)  0.000129
7     (1, 1, 1, 2, 2)  0.000129
8     (1, 1, 1, 2, 3)  0.000129
9     (1, 1, 1, 2, 4)  0.000129
10    (1, 1, 1, 2, 5)  0.000129
11    (1, 1, 1, 2, 6)  0.000129
12    (1, 1, 1, 3, 1)  0.000129
13    (1, 1, 1, 3, 2)  0.000129
14    (1, 1, 1, 3, 3)  0.000129
15    (1, 1, 1, 3, 4)  0.000129
16    (1, 1, 1, 3, 5)  0.000129
17    (1, 1, 1, 3, 6)  0.000129
18    (1, 1, 1, 4, 1)  0.000129
19    (1, 1, 1, 4, 2)  0.000129
20    (1, 1, 1, 4, 3)  0.000129
21    (1, 1, 1, 4, 4)  0.000129
22    (1, 1, 1, 4, 5)  0.000129
23    (1, 1, 1, 4, 6)  0.000129
24    (1, 1, 1, 5, 1)  0.000129
25    (1, 1, 1, 5, 2)  0.000129
26    (1, 1, 1, 5, 3)  0.000129
27    (1, 1, 1, 5, 4)  0.000129
28    (1, 1, 1, 5, 5)  0.000129
29    (1, 1, 1, 5, 6)  0.000129
30    (1, 1, 1, 6, 1)  0.000129
31    (1, 1, 1, 6, 2)  0.000129
32    (1, 1, 1, 6, 3)  0.000129
33    (1, 1, 1, 6, 4)  0.000129
34    (1, 1, 1, 6, 5)  0.000129
35    (1, 1, 1, 6, 6)  0.000129
36    (1, 1, 2, 1, 1)  0.000129
37    (1, 1, 2, 1, 2)  0.000129
38    (1, 1, 2, 1, 3)  0.000129
39    (1, 1, 2, 1, 4)  0.000129
40    (1, 1, 2, 1, 5)  0.000129
41    (1, 1, 2, 1, 6)  0.000129
42    (1, 1, 2, 2, 1)  0.000129
43    (1, 1, 2, 2, 2)  0.000129
44    (1, 1, 2, 2, 3)  0.000129
45    (1, 1, 2, 2, 4)  0.000129
46    (1, 1, 2, 2, 5)  0.000129
47    (1, 1, 2, 2, 6)  0.000129
48    (1, 1, 2, 3, 1)  0.000129
49    (1, 1, 2, 3, 2)  0.000129
50    (1, 1, 2, 3, 3)  0.000129
51    (1, 1, 2, 3, 4)  0.000129
52    (1, 1, 2, 3, 5)  0.000129
53    (1, 1, 2, 3, 6)  0.000129
54    (1, 1, 2, 4, 1)  0.000129
55    (1, 1, 2, 4, 2)  0.000129
56    (1, 1, 2, 4, 3)  0.000129
57    (1, 1, 2, 4, 4)  0.000129
58    (1, 1, 2, 4, 5)  0.000129
59    (1, 1, 2, 4, 6)  0.000129
60    (1, 1, 2, 5, 1)  0.000129
61    (1, 1, 2, 5, 2)  0.000129
62    (1, 1, 2, 5, 3)  0.000129
63    (1, 1, 2, 5, 4)  0.000129
64    (1, 1, 2, 5, 5)  0.000129
65    (1, 1, 2, 5, 6)  0.000129
66    (1, 1, 2, 6, 1)  0.000129
67    (1, 1, 2, 6, 2)  0.000129
68    (1, 1, 2, 6, 3)  0.000129
69    (1, 1, 2, 6, 4)  0.000129
70    (1, 1, 2, 6, 5)  0.000129
71    (1, 1, 2, 6, 6)  0.000129
72    (1, 1, 3, 1, 1)  0.000129
73    (1, 1, 3, 1, 2)  0.000129
74    (1, 1, 3, 1, 3)  0.000129
75    (1, 1, 3, 1, 4)  0.000129
76    (1, 1, 3, 1, 5)  0.000129
77    (1, 1, 3, 1, 6)  0.000129
78    (1, 1, 3, 2, 1)  0.000129
79    (1, 1, 3, 2, 2)  0.000129
80    (1, 1, 3, 2, 3)  0.000129
81    (1, 1, 3, 2, 4)  0.000129
82    (1, 1, 3, 2, 5)  0.000129
83    (1, 1, 3, 2, 6)  0.000129
84    (1, 1, 3, 3, 1)  0.000129
85    (1, 1, 3, 3, 2)  0.000129
86    (1, 1, 3, 3, 3)  0.000129
87    (1, 1, 3, 3, 4)  0.000129
88    (1, 1, 3, 3, 5)  0.000129
89    (1, 1, 3, 3, 6)  0.000129
90    (1, 1, 3, 4, 1)  0.000129
91    (1, 1, 3, 4, 2)  0.000129
92    (1, 1, 3, 4, 3)  0.000129
93    (1, 1, 3, 4, 4)  0.000129
94    (1, 1, 3, 4, 5)  0.000129
95    (1, 1, 3, 4, 6)  0.000129
96    (1, 1, 3, 5, 1)  0.000129
97    (1, 1, 3, 5, 2)  0.000129
98    (1, 1, 3, 5, 3)  0.000129
99    (1, 1, 3, 5, 4)  0.000129
100   (1, 1, 3, 5, 5)  0.000129
101   (1, 1, 3, 5, 6)  0.000129
102   (1, 1, 3, 6, 1)  0.000129
103   (1, 1, 3, 6, 2)  0.000129
104   (1, 1, 3, 6, 3)  0.000129
105   (1, 1, 3, 6, 4)  0.000129
106   (1, 1, 3, 6, 5)  0.000129
107   (1, 1, 3, 6, 6)  0.000129
108   (1, 1, 4, 1, 1)  0.000129
109   (1, 1, 4, 1, 2)  0.000129
110   (1, 1, 4, 1, 3)  0.000129
111   (1, 1, 4, 1, 4)  0.000129
112   (1, 1, 4, 1, 5)  0.000129
113   (1, 1, 4, 1, 6)  0.000129
114   (1, 1, 4, 2, 1)  0.000129
115   (1, 1, 4, 2, 2)  0.000129
116   (1, 1, 4, 2, 3)  0.000129
117   (1, 1, 4, 2, 4)  0.000129
118   (1, 1, 4, 2, 5)  0.000129
119   (1, 1, 4, 2, 6)  0.000129
120   (1, 1, 4, 3, 1)  0.000129
121   (1, 1, 4, 3, 2)  0.000129
122   (1, 1, 4, 3, 3)  0.000129
123   (1, 1, 4, 3, 4)  0.000129
124   (1, 1, 4, 3, 5)  0.000129
125   (1, 1, 4, 3, 6)  0.000129
126   (1, 1, 4, 4, 1)  0.000129
127   (1, 1, 4, 4, 2)  0.000129
128   (1, 1, 4, 4, 3)  0.000129
129   (1, 1, 4, 4, 4)  0.000129
130   (1, 1, 4, 4, 5)  0.000129
131   (1, 1, 4, 4, 6)  0.000129
132   (1, 1, 4, 5, 1)  0.000129
133   (1, 1, 4, 5, 2)  0.000129
134   (1, 1, 4, 5, 3)  0.000129
135   (1, 1, 4, 5, 4)  0.000129
136   (1, 1, 4, 5, 5)  0.000129
137   (1, 1, 4, 5, 6)  0.000129
138   (1, 1, 4, 6, 1)  0.000129
139   (1, 1, 4, 6, 2)  0.000129
140   (1, 1, 4, 6, 3)  0.000129
141   (1, 1, 4, 6, 4)  0.000129
142   (1, 1, 4, 6, 5)  0.000129
143   (1, 1, 4, 6, 6)  0.000129
144   (1, 1, 5, 1, 1)  0.000129
145   (1, 1, 5, 1, 2)  0.000129
146   (1, 1, 5, 1, 3)  0.000129
147   (1, 1, 5, 1, 4)  0.000129
148   (1, 1, 5, 1, 5)  0.000129
149   (1, 1, 5, 1, 6)  0.000129
150   (1, 1, 5, 2, 1)  0.000129
151   (1, 1, 5, 2, 2)  0.000129
152   (1, 1, 5, 2, 3)  0.000129
153   (1, 1, 5, 2, 4)  0.000129
154   (1, 1, 5, 2, 5)  0.000129
155   (1, 1, 5, 2, 6)  0.000129
156   (1, 1, 5, 3, 1)  0.000129
157   (1, 1, 5, 3, 2)  0.000129
158   (1, 1, 5, 3, 3)  0.000129
159   (1, 1, 5, 3, 4)  0.000129
160   (1, 1, 5, 3, 5)  0.000129
161   (1, 1, 5, 3, 6)  0.000129
162   (1, 1, 5, 4, 1)  0.000129
163   (1, 1, 5, 4, 2)  0.000129
164   (1, 1, 5, 4, 3)  0.000129
165   (1, 1, 5, 4, 4)  0.000129
166   (1, 1, 5, 4, 5)  0.000129
167   (1, 1, 5, 4, 6)  0.000129
168   (1, 1, 5, 5, 1)  0.000129
169   (1, 1, 5, 5, 2)  0.000129
170   (1, 1, 5, 5, 3)  0.000129
171   (1, 1, 5, 5, 4)  0.000129
172   (1, 1, 5, 5, 5)  0.000129
173   (1, 1, 5, 5, 6)  0.000129
174   (1, 1, 5, 6, 1)  0.000129
175   (1, 1, 5, 6, 2)  0.000129
176   (1, 1, 5, 6, 3)  0.000129
177   (1, 1, 5, 6, 4)  0.000129
178   (1, 1, 5, 6, 5)  0.000129
179   (1, 1, 5, 6, 6)  0.000129
180   (1, 1, 6, 1, 1)  0.000129
181   (1, 1, 6, 1, 2)  0.000129
182   (1, 1, 6, 1, 3)  0.000129
183   (1, 1, 6, 1, 4)  0.000129
184   (1, 1, 6, 1, 5)  0.000129
185   (1, 1, 6, 1, 6)  0.000129
186   (1, 1, 6, 2, 1)  0.000129
187   (1, 1, 6, 2, 2)  0.000129
188   (1, 1, 6, 2, 3)  0.000129
189   (1, 1, 6, 2, 4)  0.000129
190   (1, 1, 6, 2, 5)  0.000129
191   (1, 1, 6, 2, 6)  0.000129
192   (1, 1, 6, 3, 1)  0.000129
193   (1, 1, 6, 3, 2)  0.000129
194   (1, 1, 6, 3, 3)  0.000129
195   (1, 1, 6, 3, 4)  0.000129
196   (1, 1, 6, 3, 5)  0.000129
197   (1, 1, 6, 3, 6)  0.000129
198   (1, 1, 6, 4, 1)  0.000129
199   (1, 1, 6, 4, 2)  0.000129
200   (1, 1, 6, 4, 3)  0.000129
201   (1, 1, 6, 4, 4)  0.000129
202   (1, 1, 6, 4, 5)  0.000129
203   (1, 1, 6, 4, 6)  0.000129
204   (1, 1, 6, 5, 1)  0.000129
205   (1, 1, 6, 5, 2)  0.000129
206   (1, 1, 6, 5, 3)  0.000129
207   (1, 1, 6, 5, 4)  0.000129
208   (1, 1, 6, 5, 5)  0.000129
209   (1, 1, 6, 5, 6)  0.000129
210   (1, 1, 6, 6, 1)  0.000129
211   (1, 1, 6, 6, 2)  0.000129
212   (1, 1, 6, 6, 3)  0.000129
213   (1, 1, 6, 6, 4)  0.000129
214   (1, 1, 6, 6, 5)  0.000129
215   (1, 1, 6, 6, 6)  0.000129
216   (1, 2, 1, 1, 1)  0.000129
217   (1, 2, 1, 1, 2)  0.000129
218   (1, 2, 1, 1, 3)  0.000129
219   (1, 2, 1, 1, 4)  0.000129
220   (1, 2, 1, 1, 5)  0.000129
221   (1, 2, 1, 1, 6)  0.000129
222   (1, 2, 1, 2, 1)  0.000129
223   (1, 2, 1, 2, 2)  0.000129
224   (1, 2, 1, 2, 3)  0.000129
225   (1, 2, 1, 2, 4)  0.000129
226   (1, 2, 1, 2, 5)  0.000129
227   (1, 2, 1, 2, 6)  0.000129
228   (1, 2, 1, 3, 1)  0.000129
229   (1, 2, 1, 3, 2)  0.000129
230   (1, 2, 1, 3, 3)  0.000129
231   (1, 2, 1, 3, 4)  0.000129
232   (1, 2, 1, 3, 5)  0.000129
233   (1, 2, 1, 3, 6)  0.000129
234   (1, 2, 1, 4, 1)  0.000129
235   (1, 2, 1, 4, 2)  0.000129
236   (1, 2, 1, 4, 3)  0.000129
237   (1, 2, 1, 4, 4)  0.000129
238   (1, 2, 1, 4, 5)  0.000129
239   (1, 2, 1, 4, 6)  0.000129
240   (1, 2, 1, 5, 1)  0.000129
241   (1, 2, 1, 5, 2)  0.000129
242   (1, 2, 1, 5, 3)  0.000129
243   (1, 2, 1, 5, 4)  0.000129
244   (1, 2, 1, 5, 5)  0.000129
245   (1, 2, 1, 5, 6)  0.000129
246   (1, 2, 1, 6, 1)  0.000129
247   (1, 2, 1, 6, 2)  0.000129
248   (1, 2, 1, 6, 3)  0.000129
249   (1, 2, 1, 6, 4)  0.000129
...               ...       ...
7526  (6, 5, 6, 1, 3)  0.000129
7527  (6, 5, 6, 1, 4)  0.000129
7528  (6, 5, 6, 1, 5)  0.000129
7529  (6, 5, 6, 1, 6)  0.000129
7530  (6, 5, 6, 2, 1)  0.000129
7531  (6, 5, 6, 2, 2)  0.000129
7532  (6, 5, 6, 2, 3)  0.000129
7533  (6, 5, 6, 2, 4)  0.000129
7534  (6, 5, 6, 2, 5)  0.000129
7535  (6, 5, 6, 2, 6)  0.000129
7536  (6, 5, 6, 3, 1)  0.000129
7537  (6, 5, 6, 3, 2)  0.000129
7538  (6, 5, 6, 3, 3)  0.000129
7539  (6, 5, 6, 3, 4)  0.000129
7540  (6, 5, 6, 3, 5)  0.000129
7541  (6, 5, 6, 3, 6)  0.000129
7542  (6, 5, 6, 4, 1)  0.000129
7543  (6, 5, 6, 4, 2)  0.000129
7544  (6, 5, 6, 4, 3)  0.000129
7545  (6, 5, 6, 4, 4)  0.000129
7546  (6, 5, 6, 4, 5)  0.000129
7547  (6, 5, 6, 4, 6)  0.000129
7548  (6, 5, 6, 5, 1)  0.000129
7549  (6, 5, 6, 5, 2)  0.000129
7550  (6, 5, 6, 5, 3)  0.000129
7551  (6, 5, 6, 5, 4)  0.000129
7552  (6, 5, 6, 5, 5)  0.000129
7553  (6, 5, 6, 5, 6)  0.000129
7554  (6, 5, 6, 6, 1)  0.000129
7555  (6, 5, 6, 6, 2)  0.000129
7556  (6, 5, 6, 6, 3)  0.000129
7557  (6, 5, 6, 6, 4)  0.000129
7558  (6, 5, 6, 6, 5)  0.000129
7559  (6, 5, 6, 6, 6)  0.000129
7560  (6, 6, 1, 1, 1)  0.000129
7561  (6, 6, 1, 1, 2)  0.000129
7562  (6, 6, 1, 1, 3)  0.000129
7563  (6, 6, 1, 1, 4)  0.000129
7564  (6, 6, 1, 1, 5)  0.000129
7565  (6, 6, 1, 1, 6)  0.000129
7566  (6, 6, 1, 2, 1)  0.000129
7567  (6, 6, 1, 2, 2)  0.000129
7568  (6, 6, 1, 2, 3)  0.000129
7569  (6, 6, 1, 2, 4)  0.000129
7570  (6, 6, 1, 2, 5)  0.000129
7571  (6, 6, 1, 2, 6)  0.000129
7572  (6, 6, 1, 3, 1)  0.000129
7573  (6, 6, 1, 3, 2)  0.000129
7574  (6, 6, 1, 3, 3)  0.000129
7575  (6, 6, 1, 3, 4)  0.000129
7576  (6, 6, 1, 3, 5)  0.000129
7577  (6, 6, 1, 3, 6)  0.000129
7578  (6, 6, 1, 4, 1)  0.000129
7579  (6, 6, 1, 4, 2)  0.000129
7580  (6, 6, 1, 4, 3)  0.000129
7581  (6, 6, 1, 4, 4)  0.000129
7582  (6, 6, 1, 4, 5)  0.000129
7583  (6, 6, 1, 4, 6)  0.000129
7584  (6, 6, 1, 5, 1)  0.000129
7585  (6, 6, 1, 5, 2)  0.000129
7586  (6, 6, 1, 5, 3)  0.000129
7587  (6, 6, 1, 5, 4)  0.000129
7588  (6, 6, 1, 5, 5)  0.000129
7589  (6, 6, 1, 5, 6)  0.000129
7590  (6, 6, 1, 6, 1)  0.000129
7591  (6, 6, 1, 6, 2)  0.000129
7592  (6, 6, 1, 6, 3)  0.000129
7593  (6, 6, 1, 6, 4)  0.000129
7594  (6, 6, 1, 6, 5)  0.000129
7595  (6, 6, 1, 6, 6)  0.000129
7596  (6, 6, 2, 1, 1)  0.000129
7597  (6, 6, 2, 1, 2)  0.000129
7598  (6, 6, 2, 1, 3)  0.000129
7599  (6, 6, 2, 1, 4)  0.000129
7600  (6, 6, 2, 1, 5)  0.000129
7601  (6, 6, 2, 1, 6)  0.000129
7602  (6, 6, 2, 2, 1)  0.000129
7603  (6, 6, 2, 2, 2)  0.000129
7604  (6, 6, 2, 2, 3)  0.000129
7605  (6, 6, 2, 2, 4)  0.000129
7606  (6, 6, 2, 2, 5)  0.000129
7607  (6, 6, 2, 2, 6)  0.000129
7608  (6, 6, 2, 3, 1)  0.000129
7609  (6, 6, 2, 3, 2)  0.000129
7610  (6, 6, 2, 3, 3)  0.000129
7611  (6, 6, 2, 3, 4)  0.000129
7612  (6, 6, 2, 3, 5)  0.000129
7613  (6, 6, 2, 3, 6)  0.000129
7614  (6, 6, 2, 4, 1)  0.000129
7615  (6, 6, 2, 4, 2)  0.000129
7616  (6, 6, 2, 4, 3)  0.000129
7617  (6, 6, 2, 4, 4)  0.000129
7618  (6, 6, 2, 4, 5)  0.000129
7619  (6, 6, 2, 4, 6)  0.000129
7620  (6, 6, 2, 5, 1)  0.000129
7621  (6, 6, 2, 5, 2)  0.000129
7622  (6, 6, 2, 5, 3)  0.000129
7623  (6, 6, 2, 5, 4)  0.000129
7624  (6, 6, 2, 5, 5)  0.000129
7625  (6, 6, 2, 5, 6)  0.000129
7626  (6, 6, 2, 6, 1)  0.000129
7627  (6, 6, 2, 6, 2)  0.000129
7628  (6, 6, 2, 6, 3)  0.000129
7629  (6, 6, 2, 6, 4)  0.000129
7630  (6, 6, 2, 6, 5)  0.000129
7631  (6, 6, 2, 6, 6)  0.000129
7632  (6, 6, 3, 1, 1)  0.000129
7633  (6, 6, 3, 1, 2)  0.000129
7634  (6, 6, 3, 1, 3)  0.000129
7635  (6, 6, 3, 1, 4)  0.000129
7636  (6, 6, 3, 1, 5)  0.000129
7637  (6, 6, 3, 1, 6)  0.000129
7638  (6, 6, 3, 2, 1)  0.000129
7639  (6, 6, 3, 2, 2)  0.000129
7640  (6, 6, 3, 2, 3)  0.000129
7641  (6, 6, 3, 2, 4)  0.000129
7642  (6, 6, 3, 2, 5)  0.000129
7643  (6, 6, 3, 2, 6)  0.000129
7644  (6, 6, 3, 3, 1)  0.000129
7645  (6, 6, 3, 3, 2)  0.000129
7646  (6, 6, 3, 3, 3)  0.000129
7647  (6, 6, 3, 3, 4)  0.000129
7648  (6, 6, 3, 3, 5)  0.000129
7649  (6, 6, 3, 3, 6)  0.000129
7650  (6, 6, 3, 4, 1)  0.000129
7651  (6, 6, 3, 4, 2)  0.000129
7652  (6, 6, 3, 4, 3)  0.000129
7653  (6, 6, 3, 4, 4)  0.000129
7654  (6, 6, 3, 4, 5)  0.000129
7655  (6, 6, 3, 4, 6)  0.000129
7656  (6, 6, 3, 5, 1)  0.000129
7657  (6, 6, 3, 5, 2)  0.000129
7658  (6, 6, 3, 5, 3)  0.000129
7659  (6, 6, 3, 5, 4)  0.000129
7660  (6, 6, 3, 5, 5)  0.000129
7661  (6, 6, 3, 5, 6)  0.000129
7662  (6, 6, 3, 6, 1)  0.000129
7663  (6, 6, 3, 6, 2)  0.000129
7664  (6, 6, 3, 6, 3)  0.000129
7665  (6, 6, 3, 6, 4)  0.000129
7666  (6, 6, 3, 6, 5)  0.000129
7667  (6, 6, 3, 6, 6)  0.000129
7668  (6, 6, 4, 1, 1)  0.000129
7669  (6, 6, 4, 1, 2)  0.000129
7670  (6, 6, 4, 1, 3)  0.000129
7671  (6, 6, 4, 1, 4)  0.000129
7672  (6, 6, 4, 1, 5)  0.000129
7673  (6, 6, 4, 1, 6)  0.000129
7674  (6, 6, 4, 2, 1)  0.000129
7675  (6, 6, 4, 2, 2)  0.000129
7676  (6, 6, 4, 2, 3)  0.000129
7677  (6, 6, 4, 2, 4)  0.000129
7678  (6, 6, 4, 2, 5)  0.000129
7679  (6, 6, 4, 2, 6)  0.000129
7680  (6, 6, 4, 3, 1)  0.000129
7681  (6, 6, 4, 3, 2)  0.000129
7682  (6, 6, 4, 3, 3)  0.000129
7683  (6, 6, 4, 3, 4)  0.000129
7684  (6, 6, 4, 3, 5)  0.000129
7685  (6, 6, 4, 3, 6)  0.000129
7686  (6, 6, 4, 4, 1)  0.000129
7687  (6, 6, 4, 4, 2)  0.000129
7688  (6, 6, 4, 4, 3)  0.000129
7689  (6, 6, 4, 4, 4)  0.000129
7690  (6, 6, 4, 4, 5)  0.000129
7691  (6, 6, 4, 4, 6)  0.000129
7692  (6, 6, 4, 5, 1)  0.000129
7693  (6, 6, 4, 5, 2)  0.000129
7694  (6, 6, 4, 5, 3)  0.000129
7695  (6, 6, 4, 5, 4)  0.000129
7696  (6, 6, 4, 5, 5)  0.000129
7697  (6, 6, 4, 5, 6)  0.000129
7698  (6, 6, 4, 6, 1)  0.000129
7699  (6, 6, 4, 6, 2)  0.000129
7700  (6, 6, 4, 6, 3)  0.000129
7701  (6, 6, 4, 6, 4)  0.000129
7702  (6, 6, 4, 6, 5)  0.000129
7703  (6, 6, 4, 6, 6)  0.000129
7704  (6, 6, 5, 1, 1)  0.000129
7705  (6, 6, 5, 1, 2)  0.000129
7706  (6, 6, 5, 1, 3)  0.000129
7707  (6, 6, 5, 1, 4)  0.000129
7708  (6, 6, 5, 1, 5)  0.000129
7709  (6, 6, 5, 1, 6)  0.000129
7710  (6, 6, 5, 2, 1)  0.000129
7711  (6, 6, 5, 2, 2)  0.000129
7712  (6, 6, 5, 2, 3)  0.000129
7713  (6, 6, 5, 2, 4)  0.000129
7714  (6, 6, 5, 2, 5)  0.000129
7715  (6, 6, 5, 2, 6)  0.000129
7716  (6, 6, 5, 3, 1)  0.000129
7717  (6, 6, 5, 3, 2)  0.000129
7718  (6, 6, 5, 3, 3)  0.000129
7719  (6, 6, 5, 3, 4)  0.000129
7720  (6, 6, 5, 3, 5)  0.000129
7721  (6, 6, 5, 3, 6)  0.000129
7722  (6, 6, 5, 4, 1)  0.000129
7723  (6, 6, 5, 4, 2)  0.000129
7724  (6, 6, 5, 4, 3)  0.000129
7725  (6, 6, 5, 4, 4)  0.000129
7726  (6, 6, 5, 4, 5)  0.000129
7727  (6, 6, 5, 4, 6)  0.000129
7728  (6, 6, 5, 5, 1)  0.000129
7729  (6, 6, 5, 5, 2)  0.000129
7730  (6, 6, 5, 5, 3)  0.000129
7731  (6, 6, 5, 5, 4)  0.000129
7732  (6, 6, 5, 5, 5)  0.000129
7733  (6, 6, 5, 5, 6)  0.000129
7734  (6, 6, 5, 6, 1)  0.000129
7735  (6, 6, 5, 6, 2)  0.000129
7736  (6, 6, 5, 6, 3)  0.000129
7737  (6, 6, 5, 6, 4)  0.000129
7738  (6, 6, 5, 6, 5)  0.000129
7739  (6, 6, 5, 6, 6)  0.000129
7740  (6, 6, 6, 1, 1)  0.000129
7741  (6, 6, 6, 1, 2)  0.000129
7742  (6, 6, 6, 1, 3)  0.000129
7743  (6, 6, 6, 1, 4)  0.000129
7744  (6, 6, 6, 1, 5)  0.000129
7745  (6, 6, 6, 1, 6)  0.000129
7746  (6, 6, 6, 2, 1)  0.000129
7747  (6, 6, 6, 2, 2)  0.000129
7748  (6, 6, 6, 2, 3)  0.000129
7749  (6, 6, 6, 2, 4)  0.000129
7750  (6, 6, 6, 2, 5)  0.000129
7751  (6, 6, 6, 2, 6)  0.000129
7752  (6, 6, 6, 3, 1)  0.000129
7753  (6, 6, 6, 3, 2)  0.000129
7754  (6, 6, 6, 3, 3)  0.000129
7755  (6, 6, 6, 3, 4)  0.000129
7756  (6, 6, 6, 3, 5)  0.000129
7757  (6, 6, 6, 3, 6)  0.000129
7758  (6, 6, 6, 4, 1)  0.000129
7759  (6, 6, 6, 4, 2)  0.000129
7760  (6, 6, 6, 4, 3)  0.000129
7761  (6, 6, 6, 4, 4)  0.000129
7762  (6, 6, 6, 4, 5)  0.000129
7763  (6, 6, 6, 4, 6)  0.000129
7764  (6, 6, 6, 5, 1)  0.000129
7765  (6, 6, 6, 5, 2)  0.000129
7766  (6, 6, 6, 5, 3)  0.000129
7767  (6, 6, 6, 5, 4)  0.000129
7768  (6, 6, 6, 5, 5)  0.000129
7769  (6, 6, 6, 5, 6)  0.000129
7770  (6, 6, 6, 6, 1)  0.000129
7771  (6, 6, 6, 6, 2)  0.000129
7772  (6, 6, 6, 6, 3)  0.000129
7773  (6, 6, 6, 6, 4)  0.000129
7774  (6, 6, 6, 6, 5)  0.000129
7775  (6, 6, 6, 6, 6)  0.000129

[7776 rows x 2 columns]

## A Function on the Outcome Space

Suppose you roll a die five times and add up the number of spots you see. If that seems artificial, be patient for a moment and you'll soon see why it's interesting.

The sum of the rolls is a numerical function on the outcome space $\Omega$  of five rolls. The sum is thus a random variable. Let's call it  $S$ . Then, formally,
$S: \Omega \rightarrow \{ 5, 6, \ldots, 30 \}$
 
The range of  $S$  is the integers 5 through 30, because each die shows at least one and at most six spots. We can also use the equivalent notation

$\Omega \stackrel{S}{\rightarrow} \{ 5, 6, \ldots, 30 \}$
 
From a computational perspective, the elements of  $\Omega$  are in the column omega of five_roll_space. Let's apply this function and create a larger table.

In [54]:
five_rolls_sum = pd.DataFrame({
    'Omega':five_rolls,
    'S(omega)':five_roll_space['Omega'].map(lambda val: sum(val)),
    'P(omega)':five_roll_probs
})
five_rolls_sum

                Omega  P(omega)  S(omega)
0     (1, 1, 1, 1, 1)  0.000129         5
1     (1, 1, 1, 1, 2)  0.000129         6
2     (1, 1, 1, 1, 3)  0.000129         7
3     (1, 1, 1, 1, 4)  0.000129         8
4     (1, 1, 1, 1, 5)  0.000129         9
5     (1, 1, 1, 1, 6)  0.000129        10
6     (1, 1, 1, 2, 1)  0.000129         6
7     (1, 1, 1, 2, 2)  0.000129         7
8     (1, 1, 1, 2, 3)  0.000129         8
9     (1, 1, 1, 2, 4)  0.000129         9
10    (1, 1, 1, 2, 5)  0.000129        10
11    (1, 1, 1, 2, 6)  0.000129        11
12    (1, 1, 1, 3, 1)  0.000129         7
13    (1, 1, 1, 3, 2)  0.000129         8
14    (1, 1, 1, 3, 3)  0.000129         9
15    (1, 1, 1, 3, 4)  0.000129        10
16    (1, 1, 1, 3, 5)  0.000129        11
17    (1, 1, 1, 3, 6)  0.000129        12
18    (1, 1, 1, 4, 1)  0.000129         8
19    (1, 1, 1, 4, 2)  0.000129         9
20    (1, 1, 1, 4, 3)  0.000129        10
21    (1, 1, 1, 4, 4)  0.000129        11
22    (1, 1, 1, 4, 5)  0.000129        12
23    (1, 1, 1, 4, 6)  0.000129        13
24    (1, 1, 1, 5, 1)  0.000129         9
25    (1, 1, 1, 5, 2)  0.000129        10
26    (1, 1, 1, 5, 3)  0.000129        11
27    (1, 1, 1, 5, 4)  0.000129        12
28    (1, 1, 1, 5, 5)  0.000129        13
29    (1, 1, 1, 5, 6)  0.000129        14
30    (1, 1, 1, 6, 1)  0.000129        10
31    (1, 1, 1, 6, 2)  0.000129        11
32    (1, 1, 1, 6, 3)  0.000129        12
33    (1, 1, 1, 6, 4)  0.000129        13
34    (1, 1, 1, 6, 5)  0.000129        14
35    (1, 1, 1, 6, 6)  0.000129        15
36    (1, 1, 2, 1, 1)  0.000129         6
37    (1, 1, 2, 1, 2)  0.000129         7
38    (1, 1, 2, 1, 3)  0.000129         8
39    (1, 1, 2, 1, 4)  0.000129         9
40    (1, 1, 2, 1, 5)  0.000129        10
41    (1, 1, 2, 1, 6)  0.000129        11
42    (1, 1, 2, 2, 1)  0.000129         7
43    (1, 1, 2, 2, 2)  0.000129         8
44    (1, 1, 2, 2, 3)  0.000129         9
45    (1, 1, 2, 2, 4)  0.000129        10
46    (1, 1, 2, 2, 5)  0.000129        11
47    (1, 1, 2, 2, 6)  0.000129        12
48    (1, 1, 2, 3, 1)  0.000129         8
49    (1, 1, 2, 3, 2)  0.000129         9
50    (1, 1, 2, 3, 3)  0.000129        10
51    (1, 1, 2, 3, 4)  0.000129        11
52    (1, 1, 2, 3, 5)  0.000129        12
53    (1, 1, 2, 3, 6)  0.000129        13
54    (1, 1, 2, 4, 1)  0.000129         9
55    (1, 1, 2, 4, 2)  0.000129        10
56    (1, 1, 2, 4, 3)  0.000129        11
57    (1, 1, 2, 4, 4)  0.000129        12
58    (1, 1, 2, 4, 5)  0.000129        13
59    (1, 1, 2, 4, 6)  0.000129        14
60    (1, 1, 2, 5, 1)  0.000129        10
61    (1, 1, 2, 5, 2)  0.000129        11
62    (1, 1, 2, 5, 3)  0.000129        12
63    (1, 1, 2, 5, 4)  0.000129        13
64    (1, 1, 2, 5, 5)  0.000129        14
65    (1, 1, 2, 5, 6)  0.000129        15
66    (1, 1, 2, 6, 1)  0.000129        11
67    (1, 1, 2, 6, 2)  0.000129        12
68    (1, 1, 2, 6, 3)  0.000129        13
69    (1, 1, 2, 6, 4)  0.000129        14
70    (1, 1, 2, 6, 5)  0.000129        15
71    (1, 1, 2, 6, 6)  0.000129        16
72    (1, 1, 3, 1, 1)  0.000129         7
73    (1, 1, 3, 1, 2)  0.000129         8
74    (1, 1, 3, 1, 3)  0.000129         9
75    (1, 1, 3, 1, 4)  0.000129        10
76    (1, 1, 3, 1, 5)  0.000129        11
77    (1, 1, 3, 1, 6)  0.000129        12
78    (1, 1, 3, 2, 1)  0.000129         8
79    (1, 1, 3, 2, 2)  0.000129         9
80    (1, 1, 3, 2, 3)  0.000129        10
81    (1, 1, 3, 2, 4)  0.000129        11
82    (1, 1, 3, 2, 5)  0.000129        12
83    (1, 1, 3, 2, 6)  0.000129        13
84    (1, 1, 3, 3, 1)  0.000129         9
85    (1, 1, 3, 3, 2)  0.000129        10
86    (1, 1, 3, 3, 3)  0.000129        11
87    (1, 1, 3, 3, 4)  0.000129        12
88    (1, 1, 3, 3, 5)  0.000129        13
89    (1, 1, 3, 3, 6)  0.000129        14
90    (1, 1, 3, 4, 1)  0.000129        10
91    (1, 1, 3, 4, 2)  0.000129        11
92    (1, 1, 3, 4, 3)  0.000129        12
93    (1, 1, 3, 4, 4)  0.000129        13
94    (1, 1, 3, 4, 5)  0.000129        14
95    (1, 1, 3, 4, 6)  0.000129        15
96    (1, 1, 3, 5, 1)  0.000129        11
97    (1, 1, 3, 5, 2)  0.000129        12
98    (1, 1, 3, 5, 3)  0.000129        13
99    (1, 1, 3, 5, 4)  0.000129        14
100   (1, 1, 3, 5, 5)  0.000129        15
101   (1, 1, 3, 5, 6)  0.000129        16
102   (1, 1, 3, 6, 1)  0.000129        12
103   (1, 1, 3, 6, 2)  0.000129        13
104   (1, 1, 3, 6, 3)  0.000129        14
105   (1, 1, 3, 6, 4)  0.000129        15
106   (1, 1, 3, 6, 5)  0.000129        16
107   (1, 1, 3, 6, 6)  0.000129        17
108   (1, 1, 4, 1, 1)  0.000129         8
109   (1, 1, 4, 1, 2)  0.000129         9
110   (1, 1, 4, 1, 3)  0.000129        10
111   (1, 1, 4, 1, 4)  0.000129        11
112   (1, 1, 4, 1, 5)  0.000129        12
113   (1, 1, 4, 1, 6)  0.000129        13
114   (1, 1, 4, 2, 1)  0.000129         9
115   (1, 1, 4, 2, 2)  0.000129        10
116   (1, 1, 4, 2, 3)  0.000129        11
117   (1, 1, 4, 2, 4)  0.000129        12
118   (1, 1, 4, 2, 5)  0.000129        13
119   (1, 1, 4, 2, 6)  0.000129        14
120   (1, 1, 4, 3, 1)  0.000129        10
121   (1, 1, 4, 3, 2)  0.000129        11
122   (1, 1, 4, 3, 3)  0.000129        12
123   (1, 1, 4, 3, 4)  0.000129        13
124   (1, 1, 4, 3, 5)  0.000129        14
125   (1, 1, 4, 3, 6)  0.000129        15
126   (1, 1, 4, 4, 1)  0.000129        11
127   (1, 1, 4, 4, 2)  0.000129        12
128   (1, 1, 4, 4, 3)  0.000129        13
129   (1, 1, 4, 4, 4)  0.000129        14
130   (1, 1, 4, 4, 5)  0.000129        15
131   (1, 1, 4, 4, 6)  0.000129        16
132   (1, 1, 4, 5, 1)  0.000129        12
133   (1, 1, 4, 5, 2)  0.000129        13
134   (1, 1, 4, 5, 3)  0.000129        14
135   (1, 1, 4, 5, 4)  0.000129        15
136   (1, 1, 4, 5, 5)  0.000129        16
137   (1, 1, 4, 5, 6)  0.000129        17
138   (1, 1, 4, 6, 1)  0.000129        13
139   (1, 1, 4, 6, 2)  0.000129        14
140   (1, 1, 4, 6, 3)  0.000129        15
141   (1, 1, 4, 6, 4)  0.000129        16
142   (1, 1, 4, 6, 5)  0.000129        17
143   (1, 1, 4, 6, 6)  0.000129        18
144   (1, 1, 5, 1, 1)  0.000129         9
145   (1, 1, 5, 1, 2)  0.000129        10
146   (1, 1, 5, 1, 3)  0.000129        11
147   (1, 1, 5, 1, 4)  0.000129        12
148   (1, 1, 5, 1, 5)  0.000129        13
149   (1, 1, 5, 1, 6)  0.000129        14
150   (1, 1, 5, 2, 1)  0.000129        10
151   (1, 1, 5, 2, 2)  0.000129        11
152   (1, 1, 5, 2, 3)  0.000129        12
153   (1, 1, 5, 2, 4)  0.000129        13
154   (1, 1, 5, 2, 5)  0.000129        14
155   (1, 1, 5, 2, 6)  0.000129        15
156   (1, 1, 5, 3, 1)  0.000129        11
157   (1, 1, 5, 3, 2)  0.000129        12
158   (1, 1, 5, 3, 3)  0.000129        13
159   (1, 1, 5, 3, 4)  0.000129        14
160   (1, 1, 5, 3, 5)  0.000129        15
161   (1, 1, 5, 3, 6)  0.000129        16
162   (1, 1, 5, 4, 1)  0.000129        12
163   (1, 1, 5, 4, 2)  0.000129        13
164   (1, 1, 5, 4, 3)  0.000129        14
165   (1, 1, 5, 4, 4)  0.000129        15
166   (1, 1, 5, 4, 5)  0.000129        16
167   (1, 1, 5, 4, 6)  0.000129        17
168   (1, 1, 5, 5, 1)  0.000129        13
169   (1, 1, 5, 5, 2)  0.000129        14
170   (1, 1, 5, 5, 3)  0.000129        15
171   (1, 1, 5, 5, 4)  0.000129        16
172   (1, 1, 5, 5, 5)  0.000129        17
173   (1, 1, 5, 5, 6)  0.000129        18
174   (1, 1, 5, 6, 1)  0.000129        14
175   (1, 1, 5, 6, 2)  0.000129        15
176   (1, 1, 5, 6, 3)  0.000129        16
177   (1, 1, 5, 6, 4)  0.000129        17
178   (1, 1, 5, 6, 5)  0.000129        18
179   (1, 1, 5, 6, 6)  0.000129        19
180   (1, 1, 6, 1, 1)  0.000129        10
181   (1, 1, 6, 1, 2)  0.000129        11
182   (1, 1, 6, 1, 3)  0.000129        12
183   (1, 1, 6, 1, 4)  0.000129        13
184   (1, 1, 6, 1, 5)  0.000129        14
185   (1, 1, 6, 1, 6)  0.000129        15
186   (1, 1, 6, 2, 1)  0.000129        11
187   (1, 1, 6, 2, 2)  0.000129        12
188   (1, 1, 6, 2, 3)  0.000129        13
189   (1, 1, 6, 2, 4)  0.000129        14
190   (1, 1, 6, 2, 5)  0.000129        15
191   (1, 1, 6, 2, 6)  0.000129        16
192   (1, 1, 6, 3, 1)  0.000129        12
193   (1, 1, 6, 3, 2)  0.000129        13
194   (1, 1, 6, 3, 3)  0.000129        14
195   (1, 1, 6, 3, 4)  0.000129        15
196   (1, 1, 6, 3, 5)  0.000129        16
197   (1, 1, 6, 3, 6)  0.000129        17
198   (1, 1, 6, 4, 1)  0.000129        13
199   (1, 1, 6, 4, 2)  0.000129        14
200   (1, 1, 6, 4, 3)  0.000129        15
201   (1, 1, 6, 4, 4)  0.000129        16
202   (1, 1, 6, 4, 5)  0.000129        17
203   (1, 1, 6, 4, 6)  0.000129        18
204   (1, 1, 6, 5, 1)  0.000129        14
205   (1, 1, 6, 5, 2)  0.000129        15
206   (1, 1, 6, 5, 3)  0.000129        16
207   (1, 1, 6, 5, 4)  0.000129        17
208   (1, 1, 6, 5, 5)  0.000129        18
209   (1, 1, 6, 5, 6)  0.000129        19
210   (1, 1, 6, 6, 1)  0.000129        15
211   (1, 1, 6, 6, 2)  0.000129        16
212   (1, 1, 6, 6, 3)  0.000129        17
213   (1, 1, 6, 6, 4)  0.000129        18
214   (1, 1, 6, 6, 5)  0.000129        19
215   (1, 1, 6, 6, 6)  0.000129        20
216   (1, 2, 1, 1, 1)  0.000129         6
217   (1, 2, 1, 1, 2)  0.000129         7
218   (1, 2, 1, 1, 3)  0.000129         8
219   (1, 2, 1, 1, 4)  0.000129         9
220   (1, 2, 1, 1, 5)  0.000129        10
221   (1, 2, 1, 1, 6)  0.000129        11
222   (1, 2, 1, 2, 1)  0.000129         7
223   (1, 2, 1, 2, 2)  0.000129         8
224   (1, 2, 1, 2, 3)  0.000129         9
225   (1, 2, 1, 2, 4)  0.000129        10
226   (1, 2, 1, 2, 5)  0.000129        11
227   (1, 2, 1, 2, 6)  0.000129        12
228   (1, 2, 1, 3, 1)  0.000129         8
229   (1, 2, 1, 3, 2)  0.000129         9
230   (1, 2, 1, 3, 3)  0.000129        10
231   (1, 2, 1, 3, 4)  0.000129        11
232   (1, 2, 1, 3, 5)  0.000129        12
233   (1, 2, 1, 3, 6)  0.000129        13
234   (1, 2, 1, 4, 1)  0.000129         9
235   (1, 2, 1, 4, 2)  0.000129        10
236   (1, 2, 1, 4, 3)  0.000129        11
237   (1, 2, 1, 4, 4)  0.000129        12
238   (1, 2, 1, 4, 5)  0.000129        13
239   (1, 2, 1, 4, 6)  0.000129        14
240   (1, 2, 1, 5, 1)  0.000129        10
241   (1, 2, 1, 5, 2)  0.000129        11
242   (1, 2, 1, 5, 3)  0.000129        12
243   (1, 2, 1, 5, 4)  0.000129        13
244   (1, 2, 1, 5, 5)  0.000129        14
245   (1, 2, 1, 5, 6)  0.000129        15
246   (1, 2, 1, 6, 1)  0.000129        11
247   (1, 2, 1, 6, 2)  0.000129        12
248   (1, 2, 1, 6, 3)  0.000129        13
249   (1, 2, 1, 6, 4)  0.000129        14
...               ...       ...       ...
7526  (6, 5, 6, 1, 3)  0.000129        21
7527  (6, 5, 6, 1, 4)  0.000129        22
7528  (6, 5, 6, 1, 5)  0.000129        23
7529  (6, 5, 6, 1, 6)  0.000129        24
7530  (6, 5, 6, 2, 1)  0.000129        20
7531  (6, 5, 6, 2, 2)  0.000129        21
7532  (6, 5, 6, 2, 3)  0.000129        22
7533  (6, 5, 6, 2, 4)  0.000129        23
7534  (6, 5, 6, 2, 5)  0.000129        24
7535  (6, 5, 6, 2, 6)  0.000129        25
7536  (6, 5, 6, 3, 1)  0.000129        21
7537  (6, 5, 6, 3, 2)  0.000129        22
7538  (6, 5, 6, 3, 3)  0.000129        23
7539  (6, 5, 6, 3, 4)  0.000129        24
7540  (6, 5, 6, 3, 5)  0.000129        25
7541  (6, 5, 6, 3, 6)  0.000129        26
7542  (6, 5, 6, 4, 1)  0.000129        22
7543  (6, 5, 6, 4, 2)  0.000129        23
7544  (6, 5, 6, 4, 3)  0.000129        24
7545  (6, 5, 6, 4, 4)  0.000129        25
7546  (6, 5, 6, 4, 5)  0.000129        26
7547  (6, 5, 6, 4, 6)  0.000129        27
7548  (6, 5, 6, 5, 1)  0.000129        23
7549  (6, 5, 6, 5, 2)  0.000129        24
7550  (6, 5, 6, 5, 3)  0.000129        25
7551  (6, 5, 6, 5, 4)  0.000129        26
7552  (6, 5, 6, 5, 5)  0.000129        27
7553  (6, 5, 6, 5, 6)  0.000129        28
7554  (6, 5, 6, 6, 1)  0.000129        24
7555  (6, 5, 6, 6, 2)  0.000129        25
7556  (6, 5, 6, 6, 3)  0.000129        26
7557  (6, 5, 6, 6, 4)  0.000129        27
7558  (6, 5, 6, 6, 5)  0.000129        28
7559  (6, 5, 6, 6, 6)  0.000129        29
7560  (6, 6, 1, 1, 1)  0.000129        15
7561  (6, 6, 1, 1, 2)  0.000129        16
7562  (6, 6, 1, 1, 3)  0.000129        17
7563  (6, 6, 1, 1, 4)  0.000129        18
7564  (6, 6, 1, 1, 5)  0.000129        19
7565  (6, 6, 1, 1, 6)  0.000129        20
7566  (6, 6, 1, 2, 1)  0.000129        16
7567  (6, 6, 1, 2, 2)  0.000129        17
7568  (6, 6, 1, 2, 3)  0.000129        18
7569  (6, 6, 1, 2, 4)  0.000129        19
7570  (6, 6, 1, 2, 5)  0.000129        20
7571  (6, 6, 1, 2, 6)  0.000129        21
7572  (6, 6, 1, 3, 1)  0.000129        17
7573  (6, 6, 1, 3, 2)  0.000129        18
7574  (6, 6, 1, 3, 3)  0.000129        19
7575  (6, 6, 1, 3, 4)  0.000129        20
7576  (6, 6, 1, 3, 5)  0.000129        21
7577  (6, 6, 1, 3, 6)  0.000129        22
7578  (6, 6, 1, 4, 1)  0.000129        18
7579  (6, 6, 1, 4, 2)  0.000129        19
7580  (6, 6, 1, 4, 3)  0.000129        20
7581  (6, 6, 1, 4, 4)  0.000129        21
7582  (6, 6, 1, 4, 5)  0.000129        22
7583  (6, 6, 1, 4, 6)  0.000129        23
7584  (6, 6, 1, 5, 1)  0.000129        19
7585  (6, 6, 1, 5, 2)  0.000129        20
7586  (6, 6, 1, 5, 3)  0.000129        21
7587  (6, 6, 1, 5, 4)  0.000129        22
7588  (6, 6, 1, 5, 5)  0.000129        23
7589  (6, 6, 1, 5, 6)  0.000129        24
7590  (6, 6, 1, 6, 1)  0.000129        20
7591  (6, 6, 1, 6, 2)  0.000129        21
7592  (6, 6, 1, 6, 3)  0.000129        22
7593  (6, 6, 1, 6, 4)  0.000129        23
7594  (6, 6, 1, 6, 5)  0.000129        24
7595  (6, 6, 1, 6, 6)  0.000129        25
7596  (6, 6, 2, 1, 1)  0.000129        16
7597  (6, 6, 2, 1, 2)  0.000129        17
7598  (6, 6, 2, 1, 3)  0.000129        18
7599  (6, 6, 2, 1, 4)  0.000129        19
7600  (6, 6, 2, 1, 5)  0.000129        20
7601  (6, 6, 2, 1, 6)  0.000129        21
7602  (6, 6, 2, 2, 1)  0.000129        17
7603  (6, 6, 2, 2, 2)  0.000129        18
7604  (6, 6, 2, 2, 3)  0.000129        19
7605  (6, 6, 2, 2, 4)  0.000129        20
7606  (6, 6, 2, 2, 5)  0.000129        21
7607  (6, 6, 2, 2, 6)  0.000129        22
7608  (6, 6, 2, 3, 1)  0.000129        18
7609  (6, 6, 2, 3, 2)  0.000129        19
7610  (6, 6, 2, 3, 3)  0.000129        20
7611  (6, 6, 2, 3, 4)  0.000129        21
7612  (6, 6, 2, 3, 5)  0.000129        22
7613  (6, 6, 2, 3, 6)  0.000129        23
7614  (6, 6, 2, 4, 1)  0.000129        19
7615  (6, 6, 2, 4, 2)  0.000129        20
7616  (6, 6, 2, 4, 3)  0.000129        21
7617  (6, 6, 2, 4, 4)  0.000129        22
7618  (6, 6, 2, 4, 5)  0.000129        23
7619  (6, 6, 2, 4, 6)  0.000129        24
7620  (6, 6, 2, 5, 1)  0.000129        20
7621  (6, 6, 2, 5, 2)  0.000129        21
7622  (6, 6, 2, 5, 3)  0.000129        22
7623  (6, 6, 2, 5, 4)  0.000129        23
7624  (6, 6, 2, 5, 5)  0.000129        24
7625  (6, 6, 2, 5, 6)  0.000129        25
7626  (6, 6, 2, 6, 1)  0.000129        21
7627  (6, 6, 2, 6, 2)  0.000129        22
7628  (6, 6, 2, 6, 3)  0.000129        23
7629  (6, 6, 2, 6, 4)  0.000129        24
7630  (6, 6, 2, 6, 5)  0.000129        25
7631  (6, 6, 2, 6, 6)  0.000129        26
7632  (6, 6, 3, 1, 1)  0.000129        17
7633  (6, 6, 3, 1, 2)  0.000129        18
7634  (6, 6, 3, 1, 3)  0.000129        19
7635  (6, 6, 3, 1, 4)  0.000129        20
7636  (6, 6, 3, 1, 5)  0.000129        21
7637  (6, 6, 3, 1, 6)  0.000129        22
7638  (6, 6, 3, 2, 1)  0.000129        18
7639  (6, 6, 3, 2, 2)  0.000129        19
7640  (6, 6, 3, 2, 3)  0.000129        20
7641  (6, 6, 3, 2, 4)  0.000129        21
7642  (6, 6, 3, 2, 5)  0.000129        22
7643  (6, 6, 3, 2, 6)  0.000129        23
7644  (6, 6, 3, 3, 1)  0.000129        19
7645  (6, 6, 3, 3, 2)  0.000129        20
7646  (6, 6, 3, 3, 3)  0.000129        21
7647  (6, 6, 3, 3, 4)  0.000129        22
7648  (6, 6, 3, 3, 5)  0.000129        23
7649  (6, 6, 3, 3, 6)  0.000129        24
7650  (6, 6, 3, 4, 1)  0.000129        20
7651  (6, 6, 3, 4, 2)  0.000129        21
7652  (6, 6, 3, 4, 3)  0.000129        22
7653  (6, 6, 3, 4, 4)  0.000129        23
7654  (6, 6, 3, 4, 5)  0.000129        24
7655  (6, 6, 3, 4, 6)  0.000129        25
7656  (6, 6, 3, 5, 1)  0.000129        21
7657  (6, 6, 3, 5, 2)  0.000129        22
7658  (6, 6, 3, 5, 3)  0.000129        23
7659  (6, 6, 3, 5, 4)  0.000129        24
7660  (6, 6, 3, 5, 5)  0.000129        25
7661  (6, 6, 3, 5, 6)  0.000129        26
7662  (6, 6, 3, 6, 1)  0.000129        22
7663  (6, 6, 3, 6, 2)  0.000129        23
7664  (6, 6, 3, 6, 3)  0.000129        24
7665  (6, 6, 3, 6, 4)  0.000129        25
7666  (6, 6, 3, 6, 5)  0.000129        26
7667  (6, 6, 3, 6, 6)  0.000129        27
7668  (6, 6, 4, 1, 1)  0.000129        18
7669  (6, 6, 4, 1, 2)  0.000129        19
7670  (6, 6, 4, 1, 3)  0.000129        20
7671  (6, 6, 4, 1, 4)  0.000129        21
7672  (6, 6, 4, 1, 5)  0.000129        22
7673  (6, 6, 4, 1, 6)  0.000129        23
7674  (6, 6, 4, 2, 1)  0.000129        19
7675  (6, 6, 4, 2, 2)  0.000129        20
7676  (6, 6, 4, 2, 3)  0.000129        21
7677  (6, 6, 4, 2, 4)  0.000129        22
7678  (6, 6, 4, 2, 5)  0.000129        23
7679  (6, 6, 4, 2, 6)  0.000129        24
7680  (6, 6, 4, 3, 1)  0.000129        20
7681  (6, 6, 4, 3, 2)  0.000129        21
7682  (6, 6, 4, 3, 3)  0.000129        22
7683  (6, 6, 4, 3, 4)  0.000129        23
7684  (6, 6, 4, 3, 5)  0.000129        24
7685  (6, 6, 4, 3, 6)  0.000129        25
7686  (6, 6, 4, 4, 1)  0.000129        21
7687  (6, 6, 4, 4, 2)  0.000129        22
7688  (6, 6, 4, 4, 3)  0.000129        23
7689  (6, 6, 4, 4, 4)  0.000129        24
7690  (6, 6, 4, 4, 5)  0.000129        25
7691  (6, 6, 4, 4, 6)  0.000129        26
7692  (6, 6, 4, 5, 1)  0.000129        22
7693  (6, 6, 4, 5, 2)  0.000129        23
7694  (6, 6, 4, 5, 3)  0.000129        24
7695  (6, 6, 4, 5, 4)  0.000129        25
7696  (6, 6, 4, 5, 5)  0.000129        26
7697  (6, 6, 4, 5, 6)  0.000129        27
7698  (6, 6, 4, 6, 1)  0.000129        23
7699  (6, 6, 4, 6, 2)  0.000129        24
7700  (6, 6, 4, 6, 3)  0.000129        25
7701  (6, 6, 4, 6, 4)  0.000129        26
7702  (6, 6, 4, 6, 5)  0.000129        27
7703  (6, 6, 4, 6, 6)  0.000129        28
7704  (6, 6, 5, 1, 1)  0.000129        19
7705  (6, 6, 5, 1, 2)  0.000129        20
7706  (6, 6, 5, 1, 3)  0.000129        21
7707  (6, 6, 5, 1, 4)  0.000129        22
7708  (6, 6, 5, 1, 5)  0.000129        23
7709  (6, 6, 5, 1, 6)  0.000129        24
7710  (6, 6, 5, 2, 1)  0.000129        20
7711  (6, 6, 5, 2, 2)  0.000129        21
7712  (6, 6, 5, 2, 3)  0.000129        22
7713  (6, 6, 5, 2, 4)  0.000129        23
7714  (6, 6, 5, 2, 5)  0.000129        24
7715  (6, 6, 5, 2, 6)  0.000129        25
7716  (6, 6, 5, 3, 1)  0.000129        21
7717  (6, 6, 5, 3, 2)  0.000129        22
7718  (6, 6, 5, 3, 3)  0.000129        23
7719  (6, 6, 5, 3, 4)  0.000129        24
7720  (6, 6, 5, 3, 5)  0.000129        25
7721  (6, 6, 5, 3, 6)  0.000129        26
7722  (6, 6, 5, 4, 1)  0.000129        22
7723  (6, 6, 5, 4, 2)  0.000129        23
7724  (6, 6, 5, 4, 3)  0.000129        24
7725  (6, 6, 5, 4, 4)  0.000129        25
7726  (6, 6, 5, 4, 5)  0.000129        26
7727  (6, 6, 5, 4, 6)  0.000129        27
7728  (6, 6, 5, 5, 1)  0.000129        23
7729  (6, 6, 5, 5, 2)  0.000129        24
7730  (6, 6, 5, 5, 3)  0.000129        25
7731  (6, 6, 5, 5, 4)  0.000129        26
7732  (6, 6, 5, 5, 5)  0.000129        27
7733  (6, 6, 5, 5, 6)  0.000129        28
7734  (6, 6, 5, 6, 1)  0.000129        24
7735  (6, 6, 5, 6, 2)  0.000129        25
7736  (6, 6, 5, 6, 3)  0.000129        26
7737  (6, 6, 5, 6, 4)  0.000129        27
7738  (6, 6, 5, 6, 5)  0.000129        28
7739  (6, 6, 5, 6, 6)  0.000129        29
7740  (6, 6, 6, 1, 1)  0.000129        20
7741  (6, 6, 6, 1, 2)  0.000129        21
7742  (6, 6, 6, 1, 3)  0.000129        22
7743  (6, 6, 6, 1, 4)  0.000129        23
7744  (6, 6, 6, 1, 5)  0.000129        24
7745  (6, 6, 6, 1, 6)  0.000129        25
7746  (6, 6, 6, 2, 1)  0.000129        21
7747  (6, 6, 6, 2, 2)  0.000129        22
7748  (6, 6, 6, 2, 3)  0.000129        23
7749  (6, 6, 6, 2, 4)  0.000129        24

### Functions of Random Variables,
A random variable is a numerical function on  $\Omega$ . Therefore by composition, a numerical function of a random variable is also a random variable.

For example,  $S^2$  is a random variable, calculated as follows:

$S^2(\omega) = \big{(} S(\omega)\big{)}^2$
 
Thus for example  $S^2(\text{[6 6 6 6 6]}) = 30^2 = 900$.

### Events Determined by $S$ ###
From the table `five_rolls_sum` it is hard to tell how many rows show a sum of 6, or 10, or any other value. To better understand the properties of $S$, we have to organize the information in `five_rolls_sum`.

For any subset $A$ of the range of $S$, define the event $\{S \in A\}$ as

$$
\{S \in A \} = \{\omega: S(\omega) \in A \}
$$

That is, $\{ S \in A\}$ is the collection of all $\omega$ for which $S(\omega)$ is in $A$.

If that definition looks unfriendly, try it out in a special case. Take $A = \{5, 30\}$. Then $\{S \in A\}$ if and only if either all the rolls show 1 spot or all the rolls show 6 spots. So 
$$
\{S \in A\} = \{\text{[1 1 1 1 1], [6 6 6 6 6]}\}
$$

It is natural to ask about the chance the sum is a particular value, say 10. That's not easy to read off the table, but we can access the corresponding rows:

In [60]:
five_rolls_sum[five_rolls_sum['S(omega)']==10]

                Omega  P(omega)  S(omega)
5     (1, 1, 1, 1, 6)  0.000129        10
10    (1, 1, 1, 2, 5)  0.000129        10
15    (1, 1, 1, 3, 4)  0.000129        10
20    (1, 1, 1, 4, 3)  0.000129        10
25    (1, 1, 1, 5, 2)  0.000129        10
30    (1, 1, 1, 6, 1)  0.000129        10
40    (1, 1, 2, 1, 5)  0.000129        10
45    (1, 1, 2, 2, 4)  0.000129        10
50    (1, 1, 2, 3, 3)  0.000129        10
55    (1, 1, 2, 4, 2)  0.000129        10
60    (1, 1, 2, 5, 1)  0.000129        10
75    (1, 1, 3, 1, 4)  0.000129        10
80    (1, 1, 3, 2, 3)  0.000129        10
85    (1, 1, 3, 3, 2)  0.000129        10
90    (1, 1, 3, 4, 1)  0.000129        10
110   (1, 1, 4, 1, 3)  0.000129        10
115   (1, 1, 4, 2, 2)  0.000129        10
120   (1, 1, 4, 3, 1)  0.000129        10
145   (1, 1, 5, 1, 2)  0.000129        10
150   (1, 1, 5, 2, 1)  0.000129        10
180   (1, 1, 6, 1, 1)  0.000129        10
220   (1, 2, 1, 1, 5)  0.000129        10
225   (1, 2, 1, 2, 4)  0.000129        10
230   (1, 2, 1, 3, 3)  0.000129        10
235   (1, 2, 1, 4, 2)  0.000129        10
240   (1, 2, 1, 5, 1)  0.000129        10
255   (1, 2, 2, 1, 4)  0.000129        10
260   (1, 2, 2, 2, 3)  0.000129        10
265   (1, 2, 2, 3, 2)  0.000129        10
270   (1, 2, 2, 4, 1)  0.000129        10
290   (1, 2, 3, 1, 3)  0.000129        10
295   (1, 2, 3, 2, 2)  0.000129        10
300   (1, 2, 3, 3, 1)  0.000129        10
325   (1, 2, 4, 1, 2)  0.000129        10
330   (1, 2, 4, 2, 1)  0.000129        10
360   (1, 2, 5, 1, 1)  0.000129        10
435   (1, 3, 1, 1, 4)  0.000129        10
440   (1, 3, 1, 2, 3)  0.000129        10
445   (1, 3, 1, 3, 2)  0.000129        10
450   (1, 3, 1, 4, 1)  0.000129        10
470   (1, 3, 2, 1, 3)  0.000129        10
475   (1, 3, 2, 2, 2)  0.000129        10
480   (1, 3, 2, 3, 1)  0.000129        10
505   (1, 3, 3, 1, 2)  0.000129        10
510   (1, 3, 3, 2, 1)  0.000129        10
540   (1, 3, 4, 1, 1)  0.000129        10
650   (1, 4, 1, 1, 3)  0.000129        10
655   (1, 4, 1, 2, 2)  0.000129        10
660   (1, 4, 1, 3, 1)  0.000129        10
685   (1, 4, 2, 1, 2)  0.000129        10
690   (1, 4, 2, 2, 1)  0.000129        10
720   (1, 4, 3, 1, 1)  0.000129        10
865   (1, 5, 1, 1, 2)  0.000129        10
870   (1, 5, 1, 2, 1)  0.000129        10
900   (1, 5, 2, 1, 1)  0.000129        10
1080  (1, 6, 1, 1, 1)  0.000129        10
1300  (2, 1, 1, 1, 5)  0.000129        10
1305  (2, 1, 1, 2, 4)  0.000129        10
1310  (2, 1, 1, 3, 3)  0.000129        10
1315  (2, 1, 1, 4, 2)  0.000129        10
1320  (2, 1, 1, 5, 1)  0.000129        10
1335  (2, 1, 2, 1, 4)  0.000129        10
1340  (2, 1, 2, 2, 3)  0.000129        10
1345  (2, 1, 2, 3, 2)  0.000129        10
1350  (2, 1, 2, 4, 1)  0.000129        10
1370  (2, 1, 3, 1, 3)  0.000129        10
1375  (2, 1, 3, 2, 2)  0.000129        10
1380  (2, 1, 3, 3, 1)  0.000129        10
1405  (2, 1, 4, 1, 2)  0.000129        10
1410  (2, 1, 4, 2, 1)  0.000129        10
1440  (2, 1, 5, 1, 1)  0.000129        10
1515  (2, 2, 1, 1, 4)  0.000129        10
1520  (2, 2, 1, 2, 3)  0.000129        10
1525  (2, 2, 1, 3, 2)  0.000129        10
1530  (2, 2, 1, 4, 1)  0.000129        10
1550  (2, 2, 2, 1, 3)  0.000129        10
1555  (2, 2, 2, 2, 2)  0.000129        10
1560  (2, 2, 2, 3, 1)  0.000129        10
1585  (2, 2, 3, 1, 2)  0.000129        10
1590  (2, 2, 3, 2, 1)  0.000129        10
1620  (2, 2, 4, 1, 1)  0.000129        10
1730  (2, 3, 1, 1, 3)  0.000129        10
1735  (2, 3, 1, 2, 2)  0.000129        10
1740  (2, 3, 1, 3, 1)  0.000129        10
1765  (2, 3, 2, 1, 2)  0.000129        10
1770  (2, 3, 2, 2, 1)  0.000129        10
1800  (2, 3, 3, 1, 1)  0.000129        10
1945  (2, 4, 1, 1, 2)  0.000129        10
1950  (2, 4, 1, 2, 1)  0.000129        10
1980  (2, 4, 2, 1, 1)  0.000129        10
2160  (2, 5, 1, 1, 1)  0.000129        10
2595  (3, 1, 1, 1, 4)  0.000129        10
2600  (3, 1, 1, 2, 3)  0.000129        10
2605  (3, 1, 1, 3, 2)  0.000129        10
2610  (3, 1, 1, 4, 1)  0.000129        10
2630  (3, 1, 2, 1, 3)  0.000129        10
2635  (3, 1, 2, 2, 2)  0.000129        10
2640  (3, 1, 2, 3, 1)  0.000129        10
2665  (3, 1, 3, 1, 2)  0.000129        10
2670  (3, 1, 3, 2, 1)  0.000129        10
2700  (3, 1, 4, 1, 1)  0.000129        10
2810  (3, 2, 1, 1, 3)  0.000129        10
2815  (3, 2, 1, 2, 2)  0.000129        10
2820  (3, 2, 1, 3, 1)  0.000129        10
2845  (3, 2, 2, 1, 2)  0.000129        10
2850  (3, 2, 2, 2, 1)  0.000129        10
2880  (3, 2, 3, 1, 1)  0.000129        10
3025  (3, 3, 1, 1, 2)  0.000129        10
3030  (3, 3, 1, 2, 1)  0.000129        10
3060  (3, 3, 2, 1, 1)  0.000129        10
3240  (3, 4, 1, 1, 1)  0.000129        10
3890  (4, 1, 1, 1, 3)  0.000129        10
3895  (4, 1, 1, 2, 2)  0.000129        10
3900  (4, 1, 1, 3, 1)  0.000129        10
3925  (4, 1, 2, 1, 2)  0.000129        10
3930  (4, 1, 2, 2, 1)  0.000129        10
3960  (4, 1, 3, 1, 1)  0.000129        10
4105  (4, 2, 1, 1, 2)  0.000129        10
4110  (4, 2, 1, 2, 1)  0.000129        10
4140  (4, 2, 2, 1, 1)  0.000129        10
4320  (4, 3, 1, 1, 1)  0.000129        10
5185  (5, 1, 1, 1, 2)  0.000129        10
5190  (5, 1, 1, 2, 1)  0.000129        10
5220  (5, 1, 2, 1, 1)  0.000129        10
5400  (5, 2, 1, 1, 1)  0.000129        10
6480  (6, 1, 1, 1, 1)  0.000129        10

There are 126 values of $\omega$ for which $S(\omega) = 10$. Since all the $\omega$ are equally likely, the chance that $S$ has the value 10 is 126/7776. 

We are informal with notation and write $\{ S = 10 \}$ instead of $\{ S \in \{10\} \}$:
$$
P(S = 10) = \frac{126}{7776} = 1.62\%
$$

### This is how Random Variables help us quantify the results of experiments for the purpose of analysis. 
i.e., Random variables provide *numerical* summaries of the experiment in question. - Stats110 harvard (also below paragraph)

>This definition is abstract but fundamental; one of the most important skills to
develop when studying probability and statistics is the ability to go back and forth
between abstract ideas and concrete examples. Relatedly, it is important to work
on recognizing the essential pattern or structure of a problem and how it connectsto problems you have studied previously. We will often discuss stories that involve
tossing coins or drawing balls from urns because they are simple, convenient sce-
narios to work with, but many other problems are isomorphic: they have the same
essential structure, but in a different guise.

we can use mathematical opeartion on these variables since they are real valued function nowto problems you have studied previously. We will often discuss stories that involve
tossing coins or drawing balls from urns because they are simple, convenient sce-
narios to work with, but many other problems are isomorphic: they have the same
essential structure, but in a diâ†µerent guise.